### ISSUE TITLE
コーディングルール

### ISSUE THREAD

**Issue by chiba-trym** [trymcom/html#2]
案件によってルールのこういった点が気になるというのが出てくると思うので意見交換したいなーとかおもってたりします。

個人的に最近気になっている点↓

**・CSSのセレクタ**

タグが変わることも想定して極力タイプセレクタを使わないほうがいいのではないかとおもっています。
もちろんaやspan等タイプセレクタの方が応用が効く場面もあるので臨機応変にかとは思いますが、、

**・IDやクラス名の区切り文字、JS用セレクタ**

クラス名が変わった時のことを考慮して極力通常のスタイリング用のクラスにjsのイベントを持たせない方が良いと思うので、専用のクラスを持たせる。

クラスに関しても見通しを良くするため状態や役割を示すクラスに関しては「js_hoge」「is_current」「is_active」の用に接頭辞をつける共に、接頭辞に関してはハイフンやアンスコを使っても良しとしてはどうでしょう？

**・common.css　メディアクエリ**

ブレークポイントをPC,TAB,SPで3つほどmixinで作って置くのはどうでしょう？
引き継ぎや更新、量産時等管理が容易かと思います。

**Comment by leo-trym** [comment]
ご提案、ありがとうございます。
ごもっともな内容でしたので、後日ルールに追記させていただきます:blush:

**Comment by santku** [comment]
こういうのいいと思います！
コーダーチームで勉強会とかズンズンやっちゃってください！

**Comment by chiba-trym** [comment]
ありがとうございますー！
勉強会に関してもみなさん知りたいことがあったり発信したいこと書いていってくれれば頑張ります。
