### ISSUE TITLE
gulpを使いたい方へ

### ISSUE THREAD

**Issue by leo-trym** [trymcom/html#3]
まだ最低限のものですが、現在のトライムでよく用いているファイル構成でも、  
動作するgulpfile.jsを作成しました。

https://gist.github.com/leo-trym/175139ca66ece1eb2d079ef328975684

gulpでしか出来ないAutoprefixer等の機能を使うと、  
koara環境でプレフィックスが消えてしまうので、  
そのあたりの機能はまだ使用しないでくださいね！

おすすめ、プラグイン等あったら↓のコメント欄などで教えてください。

**Comment by chiba-trym** [comment]
ありがとうございます。
早速使いたいと思います。

下記個人的に使っててトライムですぐ使えそうなおすすめですー
http://csscomb.com/
https://www.browsersync.io/

あと、gulp使う方はnodemoduleをgitに共有しないように気をつけてください。
また、ある程度品質保つためにプロジェクト毎にgulp.jsを共有するとか決めたほうがいいかもですね

**Comment by leo-trym** [comment]
暇な時にpackage.json作ります。

**Comment by leo-trym** [comment]
各位

うららかな春の日差しが心地よいこのごろ、  
皆様いかがお過ごしでしょうか？

さて、Gulp用のリポジトリを作成いたしました。 
今後こちらで更新していきますので、ご活用下さい。

https://github.com/trymcom/gulp

・Browsersync 導入しました。
・csscombはscssに効かせる方法を検討中。

※以上、返信不要
